In [ ]:
1.Initialize a numpy array of 5*5 dimensions with all the values to be 0


In [1]:
import numpy as np

In [4]:
np5by5 = np.zeros((5,5),dtype=int)

In [5]:
np5by5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
2.Create a numpy array with initial value 10 and final 100 with an interval of 5 between each value


In [9]:
np10to100 = np.arange(10,105,5)

In [10]:
np10to100

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [ ]:
3.Create a 2-D array with values (10,20,30,40,50,60) and set the dimension to be 2*3
a. Print the number of elements in the array
b. Get the data-type of the array


In [11]:
a = (10,20,30,40,50,60)
nprand = np.reshape(a,(2,3))

In [12]:
nprand

array([[10, 20, 30],
       [40, 50, 60]])

In [13]:
nprand.shape

(2, 3)

In [18]:
nprand.size

6

In [16]:
type(nprand)

numpy.ndarray

In [ ]:
4.Create first numpy array with values (1,2,3). Create second numpy array with values (4,5,6).
Perform simple arithmetic operations on these two numpy arrays:
a. Addition
b. Subtraction
c. Multiplication
d. Division


In [19]:
a = np.array((1,2,3))

In [21]:
type(a)

numpy.ndarray

In [22]:
b = np.array((4,5,6))

In [25]:
type(b)

numpy.ndarray

In [26]:
a

array([1, 2, 3])

In [27]:
b

array([4, 5, 6])

In [28]:
a+b

array([5, 7, 9])

In [29]:
a - b

array([-3, -3, -3])

In [30]:
b - a

array([3, 3, 3])

In [31]:
a * b

array([ 4, 10, 18])

In [32]:
a / b

array([0, 0, 0])

In [33]:
b / a

array([4, 2, 2])

In [ ]:
5.Create a numpy array with values 10-90 and set the shape to be 3*3
a. Extract only the 3rd column from the numpy array
b. Extract only the 2nd row from the numpy array
c. Extract those cells at the intersection of first two rows and first two columns


In [43]:
np10to90 = np.arange(10,91,9)

In [46]:
d = np10to90.reshape((3,3))

In [47]:
d

array([[10, 19, 28],
       [37, 46, 55],
       [64, 73, 82]])

In [48]:
d[:,2:]

array([[28],
       [55],
       [82]])

In [49]:
d[:,1:2]

array([[19],
       [46],
       [73]])

In [50]:
d[:2,:2]

array([[10, 19],
       [37, 46]])