In [ ]:
1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a
    numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
    [
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]
    ]


In [1]:
import numpy as np

In [4]:
def create_matrix(dim,number):
    a = np.ones(dim,dtype=int)
    return a*number

In [5]:
create_matrix((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
2. Create a method that takes n numpy arrays of same dimensions sums them and return the
answer.


In [8]:
def sum_arrays(*args):
    i = np.zeros_like(args[0])
    for a in args:
        i = i +a
    return i
        

In [14]:
a1 =np.array([1,1,2,2]).reshape((2,2))
a2 = np.array([1,1,2,2]).reshape((2,2))
sum_arrays(a1,a2)

array([[2, 2],
       [4, 4]])

In [ ]:
3.Given a 2 D Array of N X M Dimesion, Write a function that accepts this array as well as two
    numbers N and M. The method should return the top-left N X M sub matrix e.g:
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ]
        
    top_left_sub_matrix(matrix, 2, 2) -> should return :
    
        [
            [1, 2]
            [4, 5]
        ]


In [15]:
def top_left_sub_matrix(matrix,N,M):
    return matrix[:N,:M]

In [20]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
top_left_sub_matrix(a,2,2)

array([[1, 2],
       [4, 5]])

In [26]:
top_left_sub_matrix(a,1,2)

array([[1, 2]])

In [ ]:
4.Given a 2 D Array of N X M Dimesion, Write a function that accepts this array as well as two
    numbers N and M The method should return the bottom-right N X M sub matrix e.g:
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
    sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
    [
        [5, 6]
        [8, 9]
    ]

In [30]:
def  bottom_right_sub_matrix(matrix,N,M):
    r = matrix.shape[0]
    c = matrix.shape[1]
    return matrix[r-N:,c-M:]

In [31]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
bottom_right_sub_matrix(a,2,2)

array([[5, 6],
       [8, 9]])

In [ ]:
5.Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method
    should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's
    standard deviation as values:
    [1, 1, 1]
    solution(arr) -> should return :
    {'mean': 1.0, 'std_dev': 0.0}



In [40]:
def mean_and_std(l1):
    dict1 = {"mean":l1.mean(),"std_dev":l1.std()}
    return dict1


In [38]:
a = np.array([1, 2, 3,4, 5, 6,7, 8, 9])


In [41]:
mean_and_std(a)

{'mean': 5.0, 'std_dev': 2.581988897471611}

In [44]:
mean_and_std(np.array([1,1,1]))

{'mean': 1.0, 'std_dev': 0.0}